/*
 *
 * Copyright 2018 The wookey project team <wookey@ssi.gouv.fr>
 *   - Ryad     Benadjila
 *   - Arnauld  Michelizza
 *   - Mathieu  Renard
 *   - Philippe Thierry
 *   - Philippe Trebuchet
 *
 * This package is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * ur option) any later version.
 *
 * This package is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with this package; if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * This file has been generated by devheader.py from a Tataouine SDK Json layout file
 *
 */
#ifndef USB_OTG_FS_H_
# define USB_OTG_FS_H_

#include "devinfo.h"

# define USB_OTG_FS_BASE 0x50000000
#define OTG_FS_IRQ 83
#define OTG_FS_WKUP_IRQ 58
/* naming indexes in structure gpios[] table */
#define USB_FS_SOF 0
#define USB_FS_VBUS 1
#define USB_FS_DM 2
#define USB_FS_DP 3

static const struct user_driver_device_infos usb_otg_fs_dev_infos = {
    .address = 0x50000000,
    .size    = 0x4000,
    .id      = 6,
    .gpios = {
      { GPIO_PA, 8 },
      { GPIO_PA, 9 },
      { GPIO_PA, 11 },
      { GPIO_PA, 12 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
      { 0, 0 },
    }
};


#endif
