/*
 *
 * Copyright 2018 The wookey project team <wookey@ssi.gouv.fr>
 *   - Ryad     Benadjila
 *   - Arnauld  Michelizza
 *   - Mathieu  Renard
 *   - Philippe Thierry
 *   - Philippe Trebuchet
 *
 * This package is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * ur option) any later version.
 *
 * This package is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with this package; if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 *
 */
#ifndef USB_CTRL_DESCRIPTORS_H_
#define USB_CTRL_DESCRIPTORS_H_


/*
 * This is the central USB control descriptors configuration and description.
 *
 * USB descriptors types are declared here and generated by the libusbctrl based on
 * the various informations declared by the upper libraries (libbulk, libhid,
 * libscsi...) in order to declare the device interface to the host.
 *
 * EP identifiers are generated depending on the interface declaration order.
 */



#endif/*!USB_CTRL_DESCRIPTORS_H_*/
