all:
	pdflatex rapport_ESSI.tex
	pdflatex rapport_ESSI.tex
#	bibtex rapport_ESSI.aux


clean:
	rm -f rapport_ESSI.blg rapport_ESSI.bbl rapport_ESSI.toc rapport_ESSI.out rapport_ESSI.aux rapport_ESSI.pdf rapport_ESSI.log
