all:
	pdflatex soutenance_ESSI.tex
	pdflatex soutenance_ESSI.tex

clean:
	rm -f soutenance_ESSI.blg soutenance_ESSI.bbl soutenance_ESSI.toc soutenance_ESSI.out soutenance_ESSI.aux soutenance_ESSI.pdf soutenance_ESSI.log soutenance_ESSI.nav soutenance_EESI.snm
